version: '2'

services:
  uf-web:
    image: unifield/web:2.1-3rc3
    ports:
     - "8061:8061"
    depends_on:
     - uf-server
  uf-server:
    image: unifield/server:2.1-3rc3
    ports:
     - "8069"
     - "8070"
     - "8071"
    depends_on:
     - db
    links:
     - "db:database"
  db:
    image: postgres:9.4
    ports:
     - "5432"
    environment:
     - "POSTGRES_USER=unifield"
    volumes:
     - /var/lib/postgresql/data
