FROM python:2.7

RUN	echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
	wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
	apt-get update && \
	apt-get install -y --no-install-recommends \
		postgresql-client-common \
		postgresql-client-8.4 \
		net-tools \
	&& apt-get clean

ADD requirements.txt /opt/unifield/requirements.txt
RUN pip install -r /opt/unifield/requirements.txt
RUN groupadd -r unifield && useradd -r -g unifield unifield && \
	chown unifield:unifield /opt/unifield

# Set the timezone to match what is set in
# github.com/Unifield/docker-psql8.4/Dockerfile
RUN echo "Europe/Paris" > /etc/timezone && \
	dpkg-reconfigure -f noninteractive tzdata 
