FROM python:2.7
RUN	apt-get update && \
	apt-get install -y --no-install-recommends \
		postgresql-client-common \
		postgresql-client-9.4 \
	&& apt-get clean
ADD requirements.txt /opt/unifield/requirements.txt
RUN pip install -r /opt/unifield/requirements.txt
RUN groupadd -r unifield && useradd -r -g unifield unifield && \
	chown unifield:unifield /opt/unifield
